import os
from dotenv import load_dotenv

load_dotenv()

WEATHER_API_KEY = os.getenv("WEATHER_API_KEY")

SERVICENOW_INSTANCE_URL = os.getenv(
    "SERVICENOW_INSTANCE_URL",
    "https://dev374413.service-now.com",
)
SERVICENOW_USERNAME = os.getenv("SERVICENOW_USERNAME")
SERVICENOW_PASSWORD = os.getenv("SERVICENOW_PASSWORD")
SERVICENOW_INCIDENT_SYS_ID = os.getenv("SERVICENOW_INCIDENT_SYS_ID")
SERVICENOW_INCIDENT_NUMBER = os.getenv("SERVICENOW_INCIDENT_NUMBER")
SERVICENOW_NOTE_FIELD = os.getenv("SERVICENOW_NOTE_FIELD", "work_notes")
